version: '3.7'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - zk

  # use zookeeper:2181 for the connection string
  zoonavigator:
    image: elkozmon/zoonavigator
    ports: ["9000:9000"]
    environment: ["HTTP_PORT=9000"]
    depends_on: ["zookeeper"]
    networks: ["zk"]


  # kafka:
  #   image: wurstmeister/kafka
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #   volumes:
  #     - kafka-data:/var/lib/kafka/data
  #   networks:
  #     - zk
  #   depends_on: ["zookeeper"]


networks:
  zk:
    name: zk
    driver: bridge


volumes:
  kafka-data:
